// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbafxgtmzcsynkfhbmpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiYWZ4Z3RtemNzeW5rZmhibXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NzgwMTcsImV4cCI6MjA1ODI1NDAxN30.WRpjen6eUmuuGES2hJnwZbDGzYUA5J_J3wmjFd-431o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);